language: node_js
node_js:
- 8.4.0
notifications:
  email: false
before_install:
- npm i -g npm@latest
cache:
  directories:
  - node_modules
after_success: npm run coveralls
before_deploy:
- npm run build && rm -rf specs-editor && npm pack
deploy:
- provider: releases
  api_key:
    secure: "GrulTJIEv3tvqNv0ALy6zU2Apq6WxcSUxxmK5DUFKLKYP00lDUABtyYrJILfP6mKL4ofXHGO71ylxuNeJCMjiR84wDjZVaFEL83pFvJl6fyGWe12IXbjy5iv8Q0ocx9oB51rfLiXsqmf2m96ZE8/iqLMikG1mtS3FPJ93L9o4zXyjXFI9NuwxYr43OGvxqQULp7K16oGiT9iQ9Ou9kvh0J5NkPrRcNnIl9K/sgae76nEdG7kx0T8+2++Zo9GhIiumFPojWz1drWqgDOeJPKpnclJBz9xMbF5pPcEIvpkiVm6AmfjMXeE7dZbaDqIlVqtq6Y8sfHJUT6BiHL5O7PW8LbEUQi98sMOwU+BLOz5TSjG/ieT6Thutwb71S22KCerIZ43DSAhB7+W+dZwHSSY+h8yeabCQAsKxFHGV0/RZWexQUQ2ZrZ0ccjhHO4pneiG3TgoUlbUTq6oAMZuWbinhUYAkxF3RX9yFF+RneCxV6UWZHiYh7suGpvGogR+X0wyC+Xb1CMRTAmaIwflTOUos7E3o4G1hbg26Fz4PUpkq8fbp+Uc5QqptYLxE+lUtQ310O7A3Rz6TPXPoqKPAAG24WONRsYXBYZcFJeMPkR0dEUCwgwjgFcFUrevBaxKF8tkQJehuvIgG5mG0b1i+3L3yj1NpgwsFiWR5Z6tQxsGoVM="
  file:
  - specs-generator-${TRAVIS_TAG}.tgz
  skip_cleanup: true
  on:
    repo: opengate-io/specs-generator
    tags: true